### ISSUE TITLE
tmp_upload aspect

### ISSUE THREAD

**Issue by softwareloop** [softwareloop/uploader-plus#1]

**Comment by douglascrp** [comment]
@softwareloop Is this still an issue?

**Comment by softwareloop** [comment]
This was meant to be an alternative user interaction for uploading files, whereby the user could upload files without metadata, go away, and then come back later to finish the job by filling in the metadata. The tmp_upload aspect would mark the file as uploaded but still missing metadata.

It was just an initial thought, suggested by some discussions on the web and with real users. The design took a different direction (upload and metadata editing in one step) so this issue is no longer required. Closing it.
