### ISSUE TITLE
cm:name set as readonly

### ISSUE THREAD

**Issue by FilipBruska** [softwareloop/uploader-plus#101]
Hello softwareloop,

I am curious why cm:name is set as readonly. Is there any reason for that?

I saw this functionality has been added in issue 29:
https://github.com/softwareloop/uploader-plus/issues/29
https://github.com/softwareloop/uploader-plus/commit/ce82d663aa52e4f506174c5276400be27538cf37

It is great that cm:name is populated automatically. If it could be changed in a form, it would be even better :-)

Thank you for that addon.

Filip

**Comment by tom-vandepoele** [comment]
In uploader-plus-mixin.js

function `onMetadataFormReceived` put 
`cmNameNode.readOnly = true;`  in comment.

> This sets the front-end element so you can edit it, but isn't used anywhere yet.

in function `processMetadata` add this below the var declarations on top:

`var cmNameId = this.id + "-metadata-form_prop_cm_name",
cmNameNode = YAHOO.util.Dom.get(cmNameId);`
` if (cmNameNode) {`
            	`var fileInfo = this.fileStore[data.id];`
            	`data.name = cmNameNode.value;`
                `fileInfo.uploadData.filename = cmNameNode.value;`
            `}`

> This sets the actual upload data to use the filename from the form field

In the `if (progressInfoEl && progressInfoEl.length === 1) {` statement, add this:
`$(progressInfoEl[0]).html(data.name);`
`$(progressInfoEl[0]).parent().prop('title', data.name);`

> This shows the proper new name in the progress screen

**Comment by FilipBruska** [comment]
Hello Tom,

Thank you for the provided solution. 

Btw, I am also curious why cm:name is set as readonly. I suppose, it has been implemented as readonly from some reason. Do you have any idea?

Br,
Filip

**Comment by douglascrp** [comment]
@tom-vandepoele Can you create a pull request with your changes?
With that, we can test it and accept it if everything works as expected.

**Comment by tom-vandepoele** [comment]
I'll see if I can make the time for this today. I'll include #103 as well
