### ISSUE TITLE
Double slash included in the generated URLs

### ISSUE THREAD

**Issue by douglascrp** [softwareloop/uploader-plus#112]
While evaluating a PR, I found this little problem in two of the URL templates:

https://github.com/softwareloop/uploader-plus/blob/master/surf/src/main/amp/web/components/uploader-plus/js/uploader-plus-mixin.js#L9

https://github.com/softwareloop/uploader-plus/blob/master/surf/src/main/amp/web/components/uploader-plus/js/uploader-plus-mixin.js#L12

The final URL is like this: http://localhost:8081/share/proxy/alfresco**//**uploader-plus/allowed-content-types

**Comment by yregaieg** [comment]
I guess you can close this one

**Comment by douglascrp** [comment]
@yregaieg Yes, you are right.
Closing it.
Thank you
