### ISSUE TITLE
UP is not working properly with Alfresco 5.2

### ISSUE THREAD

**Issue by CristinaMR** [softwareloop/uploader-plus#119]
Alfresco version: Alfresco Content Service 5.2.0

Steps to reproduce it:
- Install ACS 5.2.0
- Configure it in one document library' site
- On your document library: Try to drag and drop one folder which contains some docs inside

**Expected:** It should works fine and upload that folder with others and docs inside into Alfresco
**Result:** In each document you'll find the orange colour (as uploaded failed) and no error message in your logs (catalina, alfresco or share log files).

Screenshot: 
![imagen](https://user-images.githubusercontent.com/8526270/27294972-9d95eb50-551b-11e7-9aa9-2476955d5cc6.png)

**Comment by monicakumari** [comment]
Hello,
I am also getting the same issue. Have you got any resolution. ?

Thanks.

**Comment by Fjordo** [comment]
Have you seen any error on the browser console ?
