### ISSUE TITLE
The upload dialog shows the same file name for all uploaded files

### ISSUE THREAD

**Issue by yregaieg** [softwareloop/uploader-plus#123]
When you upload multiple files with the same metadata set and you have cm:name to your form, the cm:name is hidden out from the form (which is intended and OK), but when you confirm the form, the upload begins and the upload form shows the same cm:name for all files.
Files are uploaded correctly with the correct names, but only in the upload dialog the name of the first document is shown for all documents which may result in confusion to users.

**Comment by yregaieg** [comment]
@douglascrp I am working on this now, I just filed the issue to have an issue number to track ;-)

**Comment by douglascrp** [comment]
Closing
