### ISSUE TITLE
Does not load properties from properties file

### ISSUE THREAD

**Issue by udaikumar26** [softwareloop/uploader-plus#130]
We have several custom models defined and controlled using share-config-custom.xml
For example we have something like,

<config evaluator="node-type" condition="common:errorMessage">
		<forms>
			<form>
				<field-visibility>
					<show id="common:message" />
                                 </field-visibility>
				<appearance>
                                  <field id="common:message" label-id="prop.common_message" />
                                 </appearance>
			</form>
		</forms>
	</config>

Here the label - prop.common_message is defined in slingshot.properties file. The uploader plus shows prop.common_message in the form instead of actual value from the properties file.

**Comment by udaikumar26** [comment]
fixed. issue on our side

**Comment by yregaieg** [comment]
> found that the uploader installation overwritten slingshot.properties and also share-documentlibrary-config.xml

I do not think that comment is true. But still I would like to have a better understanding on the problem you faced and on how you managed to solve it... It might help us document the addon better to avoid having other users face the same struggle !

**Comment by udaikumar26** [comment]
We have defined some custom properties in slingshot.properties file. I have placed this addon's amp file into the amp folder of our alfresco installation(where alfresco content services amp is also present) and ran apply amp file as mentioned in the documentation. After the installation found that the slingshot.properties file is overwritten
