### ISSUE TITLE
Problem with content type display in the form

### ISSUE THREAD

**Issue by udaikumar26** [softwareloop/uploader-plus#131]
We want the content type to be displayed as something like Error Message, Digital Asset etc. instead it shows as type_common_errorMessage, type_common_digitalAsset as we have defined the model names as "common:errorMessage", "common:digitalAsset".

How to make the form display content type as Error Message, Digital Asset etc.?

**Comment by yregaieg** [comment]
@udaikumar26 this is actually not an addon issue, you are missing some localization resources.
To solve your issue you should search for "Alfresco content model localization" in the community and the documentation and start from there !

**Comment by yregaieg** [comment]
closing this for now, but please feel free to re-open if you have a different opinion

**Comment by udaikumar26** [comment]
Hi,
I see that it is the way the addon is implemented. Below line of code from uploader-plus-mixin.js tells it.

                var option = new Option(this.msg("type." + current.replace(":", "_")), current, i === 0);

**Comment by yregaieg** [comment]
@udaikumar26 that's actually the way Alfresco content model localization works in share, please check out the documentation on that and you will get the confirmation that you should have localization bundles loaded in your share context with strings following this naming scheme `type.<prefix>_<typeName>` ....
