### ISSUE TITLE
Does not allow you to set up a Upload folder

### ISSUE THREAD

**Issue by marcogianini** [softwareloop/uploader-plus#132]
Good afternoon.

I upgraded from Alfresco 5.0.0 to 5201704 Comunity and in this new environment I installed Uploader Plus v.1.6 successfully.

This test environment is pointing to a production database backup (successfully).

By entering Uploader Plus settings and configuring a Upload folder, it informs you that the folder is being used but does not have any settings in Uploader Plus. It is blank.

How can I do to remove this old note that it informs that the \ xxxx folder is being used?

Thanks.

**Comment by douglascrp** [comment]
Sorry, but I could not understand what the problem is.
Can you please share any more information, like screenshots or error messages in the logs?

**Comment by marcogianini** [comment]
Good afternoon
What I want to report is that I installed uploader plus in a new installation of alfresco (only pointing to existing database) and when I was to configure Uploader Plus to a folder it said that this folder was already a Uploader Plus repository.

In the log does not display anything about this

thankful

**Comment by douglascrp** [comment]
Can you check if the problem you are facing is the same as described here? https://github.com/softwareloop/uploader-plus/issues/94

**Comment by marcogianini** [comment]
Hello Douglas
It's not the same issue #94 and #118.
I will put some screens for the proper identification of what is happening.

In the old 5.0.0 installation and postgres database outside of alfresco, the xxx folder was used in the uploader-plus settings.

When I installed a new version 201711 (in new server) pointing to this same external database and I was doing the configuration in Uploader Plus it informs that the folder is already being used by Uploader Plus. I only applied the two AMPS on alfresco.

I will attach the screen which shows that there is no configuration in Uploader-plus and the screen that displays when I try to configure Uploader Plus.

The log (Alfresco.log or Share.log) and catalina.out also do not display any errors when I'm running this activity.

Thanks
![tela uploader-plus informativo](https://user-images.githubusercontent.com/40039143/41238292-f53b6380-6d6b-11e8-81e4-768d030ebed3.JPG)
![tela uploader-plus](https://user-images.githubusercontent.com/40039143/41238293-f55f3f1c-6d6b-11e8-9970-abb2c4dcc86b.JPG)

**Comment by douglascrp** [comment]
Hello.
Sorry, but this is still not enough, as I am not able to reproduce the issue.

Can you please attach the web browser's network activity when you access and try to configure the uploader-plus folder? Maybe that will show some useful information.

When you say you installed the 2 AMP files, can you please tell me their exact names and and how you installed them (the full commands you used)?

**Comment by marcogianini** [comment]
Hello.
As for the installation of the amps, the following commands and files were used:

java -jar bin/alfresco-mnt.jar install uploader-plus-repo-1.6.amp tomcat/webapps/alfresco.war -force 
-verbose

java -jar bin/alfresco-mnt.jar install uploader-plus-surf-1.6.amp tomcat/webapps/share.war -force 
-verbose

Then I deleted the two folders inside tomcat/webapps/alfresco and share.

I started Alfresco successfully, without any kind of error.

If I create a new folder in the Alfresco repository and configure Uploader-Plus to use this folder, it works normally.

The only problem is when I will configure a folder that was used in the old version of Uploader-Plus (1.2)

As for checking network activity in the browser, I'll see how it works. If you have a way to get by, I'm grateful for the help.

**Comment by douglascrp** [comment]
Simply use the browser's developer tool. There you will have the network tab.
Browse and try to configure the folder normally, then all you have to do is to grab the activities for the uploader-plus related webscripts.

https://developers.google.com/web/tools/chrome-devtools/network-performance/

**Comment by marcogianini** [comment]
OK. Thanks.

I´ll collect and send to you.

**Comment by cahunt** [comment]
@marcogianini   Did you find any resolution to this error?
