### ISSUE TITLE
Support for Alfresco 201806GA

### ISSUE THREAD

**Issue by dhaack** [softwareloop/uploader-plus#135]
Dears, good morning.
Any support for Alfresco 201806GA?

**Comment by cahunt** [comment]
Also wondering....

**Comment by douglascrp** [comment]
@cahunt This is weird.
I asked you about the test because Alfresco 6 has received lots of changes, but in the repository side, not in the Share side.
If you have said you faced problems in the repository, I would say, ok, that can happen, but inside Share?
Can you give me the exact steps, file names and folders you used in the deployment?
Without details, it will be hard (if not impossible) to help you.

**Comment by cahunt** [comment]
Hi, I appreciate the help!

My server is Windows 2016.  I really just followed the instructions and used the files posted here:  

https://github.com/softwareloop/uploader-plus

1. Stopped Tomcat
2. Copied the amp files into the appropriate directories
3. Ran the applyamps.bat file - no errors, confirmed UploaderPlus installed.
4. Restarted Tomcat

I did reboot the whole server just to be sure that wasn't the problem.

What are the chances it's a Server 2016 vs. Ubuntu problem?

I have 5.4 Community running on Ubuntu, it works there.  Just my licensed version is on Windows (not my choice)

I rolled my server back yesterday and didn't grab the log file. Going to try it again today.

**Comment by douglascrp** [comment]
Please, can you elaborate on "Copied the v1.6 amp files into the appropriate directories"?
That is exactly the point where you can be making mistakes.

**Comment by cahunt** [comment]
Ok sure! I really just did what it said below, I did nothing more than saving the amp files to the /amps and /amps_share directories. I got the files and instructions here:

https://github.com/softwareloop/uploader-plus/wiki/Installation

Should I have done something different?

**Comment by douglascrp** [comment]
No, that is right.
If you followed exactly what the docs says, then it should work.
The important thing is to put the right AMP file in the right folder.

**Comment by douglascrp** [comment]
No, that is right.
If you followed exactly what the docs says, then it should work.
The important thing is to put the right AMP file in the right folder.

One more question... have you tried with brand new war files (alfresco.war and share.war)?

**Comment by dhaack** [comment]
@douglascrp good morning. Then the installation was done following the instructions. Everything installs. However, in Share does not appear the uploader plus menu. I think it's possible to apply the uploader plus aspect to the folder and set the types too (as we've done here), but I understand it's a problem having to do this without the menu.

**Comment by cahunt** [comment]
@dhaack Hi - you say: 

I think it's possible to apply the uploader plus aspect to the folder and set the types too (as we've done here)

Can you be more specific about how you did that with out the Menu Option?

Thanks :)

**Comment by cahunt** [comment]
@dhaack Interesting, so by using the script, you have it functioning similar to how it works in 5.2?  If so, is this something you can provide some guidance on how to do?  I'm not overly familiar with web scripts for Alfresco but willing to learn!

**Comment by douglascrp** [comment]
@dhaack Can you please execute the following and post the result here?

' ' '
java -jar bin/alfresco-mmt.jar list tomcat/webapps/alfresco.war
java -jar bin/alfresco-mmt.jar list tomcat/webapps/share.war
' ' '

**Comment by cahunt** [comment]
I used the alfresco-mmt.jar command to force the amp to install, which gave me this:

D:\alfresco>d:\java_8\jdk1.8.0_152\bin\java -jar d:\alfresco\bin\alfresco-mmt.jar list d:\alfresco\tomcat\webapps\share.war
Module 'uploader-plus-repo' installed in 'd:\alfresco\tomcat\webapps\share.war'
   -    Title:        uploader-plus-repo
   -    Version:      1.6.1801311724
   -    Install Date: Wed Oct 17 15:36:29 ADT 2018
   -    Description:   uploader-plus AMP for Alfresco repository
Module 'alfresco-rm-enterprise-share' installed in 'd:\alfresco\tomcat\webapps\share.war'
   -    Title:        AGS Enterprise Share
   -    Version:      3.0.0
   -    Install Date: Wed Oct 17 09:46:13 ADT 2018
   -    Description:   Alfresco Governance Services Enterprise Share Extension

But still doesn't work. I was so hopeful :(

**Comment by cahunt** [comment]
Hi, It does work when I install the right amps in the right place. 

Thanks for all the help!

**Comment by douglascrp** [comment]
Good
