### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by udaikumar26** [softwareloop/uploader-plus#143]
Does uploader-plus-surf v1.6 compatible with ACS 6.2.2?

**Comment by rbelfils** [comment]
Hello,
in alfresco-share-docker/Dockerfile add this line after **alfresco-mmt** command.
```
#Problem with flash and alfresco 7.1, component flash-upload was deleted
RUN rm $TOMCAT_DIR/webapps/share/WEB-INF/classes/alfresco/site-webscripts/com/softwareloop/uploader-plus/uploader/flash-upload.get*
```
![image](https://user-images.githubusercontent.com/23735835/145847880-0ffae65a-f33d-44e6-9b2c-46e31ea0e3fb.png)

Thanks to alfresco community.

**Comment by WimCrols** [comment]
Thank you @rbelfils. Works like a charm.

**Comment by douglascrp** [comment]
Can you guys test the latest version including the changes I commited today?

If it's working now, I guess we can close this issue.

**Comment by Fjordo** [comment]
I'm using the fix having no problems, I think you can close the issue

**Comment by douglascrp** [comment]
Awesome... thank you
