### ISSUE TITLE
Enforce mode

### ISSUE THREAD

**Issue by softwareloop** [softwareloop/uploader-plus#45]

**Comment by douglascrp** [comment]
@softwareloop Is this still an issue?
Do you remember what you meant by "Enforce mode"?

**Comment by softwareloop** [comment]
This was meant to be a new feature. The plugin, in the admin panel, already lets the user select which content types can be uploaded to a folder. Those content types are then offered to users as options during a file upload. However, the plugin has no control over files that enter the folder in other ways, e.g. copied from another folder.

This feature was to let uploader-plus install a rule on the folder to reject any documents that are not of the allowed types. So the settings of uploader plus could be "enforced" deeper in the repo.

I never implemented this because it seems to be beyond the scope of the plugin. Uploader-plus should be focused on the user experience of uploading files, not on repo rules.

**Comment by yregaieg** [comment]
@softwareloop I agree with you on this: this should not be a part of this plugin

**Comment by softwareloop** [comment]
Not in scope for plugin.
