### ISSUE TITLE
Deployment to artifact repository

### ISSUE THREAD

**Issue by billerby** [softwareloop/uploader-plus#56]
Thanks for a great addon. Deployment to an artifact repository like https://bintray.com/ would be great.

**Comment by softwareloop** [comment]
I'll deploy to Maven Central repo, ok?

**Comment by billerby** [comment]
If its ok with them :) I was unsure what requirements one have to fulfill for it to be accepted for maven central deployment.

**Comment by softwareloop** [comment]
They've approved my groupId and now I have the artifacts on their staging repo. So far so good.

**Comment by softwareloop** [comment]
It worked!
http://search.maven.org/#artifactdetails%7Ccom.softwareloop%7Cuploader-plus%7C1.2%7Cpom
