### ISSUE TITLE
Mimetype lost

### ISSUE THREAD

**Issue by sprouvez** [softwareloop/uploader-plus#67]
Hi,
Thanks a lot for this module.
When i upload files, the mimetype is lost for all files uploaded with this module. Mimetype is replace by "Binary File".

**Comment by softwareloop** [comment]
Thanks, I'll have a look at it

**Comment by tatatanja** [comment]
I have the same problem in Alfresco 5.0c, that the mimetype is lost for all files uploaded.

**Comment by sprouvez** [comment]
Do you have the problem with
