### ISSUE TITLE
Upload improvement

### ISSUE THREAD

**Issue by fsforna** [softwareloop/uploader-plus#77]
Dear All,
could you investigate the possibility to improve the project by adding a new feature that when the user upload files has the possibility to specify a type and metadata for the full set of uploaded files?

Thank you for your GREAT work. It should be part of Alfresco Share core.

Best Regards,
Francesco.

**Comment by mail2hemant** [comment]
Yes, allowing multiple files to tag with single document type and metadata will be great advantage to the solution.

**Comment by douglascrp** [comment]
It seems to be the same idea of the issue #62

**Comment by awster** [comment]
Are there any plans for adding this (#62, #77) feature in the near future?
Thank you for your great work.

**Comment by douglascrp** [comment]
@awster I guess there is no "plan".
The problem is that all the contributors are busy.
Could you try to implement it and share the result?

@softwareloop Can you close this one as this is a duplicate of #62 ?

**Comment by softwareloop** [comment]
Duplicate of #62
