### ISSUE TITLE
Metadata form is not shown

### ISSUE THREAD

**Issue by douglascrp** [softwareloop/uploader-plus#80]
I'm trying the latest version with 5.0.d, but after setting an allowed types list into a folder, I cannot see the form when I upload new documents.

**Comment by lutzhorn** [comment]
Yes, using the current head does not work in 5.0d. I have to deploy version 1.2 to make the moduel work on Alfresco 5.0d.

**Comment by douglascrp** [comment]
@lutzhorn the 1.2 version is considered the final version.
The version 1.3 is still in development.

**Comment by lutzhorn** [comment]
Yes, it is 1.3-SNAPSHOT. But is there anybody working on making the head of this module working in 5.0d?

**Comment by douglascrp** [comment]
I'm working on it locally, but it's not done yet.
Axel has submitted the code you see available now. I tried it and I also
found it's not working yet.

Em qua, 28 de out de 2015 10:44, Lutz Horn <notifications@github.com>
escreveu:

> Yes, it is 1.3-SNAPSHOT. But is there anybody working on making the head
> of this module working in 5.0d?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softwareloop/uploader-plus/issues/80#issuecomment-151832473>
> .
>
-- 

Douglas C. R. Paes

**Comment by douglascrp** [comment]
This issue was fixed.

Closing it
