### ISSUE TITLE
Add Support for Custom Folder Type

### ISSUE THREAD

**Issue by kylefernandadams** [softwareloop/uploader-plus#85]
It would be great to expand the functionality to support custom folder types and their associated metadata.

**Comment by lutzhorn** [comment]
What do you mean by that? What kind of customization of the upload folder to you want to make?

**Comment by douglascrp** [comment]
@kylefernandadams I believe you are mixing things here.
This addon is intended to change the **upload** process, and creating a folder is not an upload at all.

@softwareloop Please, can you close this issue?
