### ISSUE TITLE
File Upload Does not prompt with metadata form

### ISSUE THREAD

**Issue by alex4u2nv** [softwareloop/uploader-plus#86]
Clicking the File upload button to select and upload a file doesn't invoke the metadata form using chrome for testing, and deployment into Alfresco 5.0.1 using Alfresco SDK 2.1.1. This is because the SoftwareLoop.DNDUpload extensions were loaded after the options were updated to set the dndUploader in the file-upload extension.

Here's an update to get this working.
https://github.com/alex4u2nv/uploader-plus/commit/fbb8c28e32cb8e23248e8e7f4174e836a256a8b0

**Comment by douglascrp** [comment]
@softwareloop You can close this one.
